### ISSUE TITLE
merge resource duplicate value error

### ISSUE THREAD

**Issue by GowthamGnanajothi** [loopsocial/firework_android_sdk_examples#9]
Using Dependency version 

`implementation 'com.github.loopsocial:firework_sdk:5.14.7'`

When building the project I am getting duplicate resource value error as below

jetified-expandable-layout-1.6.0/res/values/values.xml:2:4: Duplicate value for resource 'attr/textStyle' with config 'DEFAULT' and product ''. Resource was previously defined here: [jetified-firework_sdk-5.14.7/res/values/values.xml:261:4:]

Is there any way to by-pass this resource conflict?

**Comment by mohsenoid** [comment]
Hey @GowthamGnanajothi,
This example repo is related to the new Android SDK version 6 which is in beta version.
Regarding v5 I believe @millylee-dev can help you.
